[package]
name = "get_other_responses"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fofa = "*"
tokio = { version = "1", features = ["full"] }